//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS_DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cierre_mes
    {
        public long id { get; set; }
        public Nullable<int> Id_Entidad { get; set; }
        public string Mes { get; set; }
        public string Anio { get; set; }
        public Nullable<double> Monto { get; set; }
        public string Detalle { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> Fecha_Proceso { get; set; }
    
        public virtual entidades entidades { get; set; }
    }
}
