//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS_DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class combo_categoria
    {
        public combo_categoria()
        {
            this.combo_sub_categoria = new HashSet<combo_sub_categoria>();
            this.ingresos = new HashSet<ingresos>();
        }
    
        public int id { get; set; }
        public Nullable<int> Id_Entidad { get; set; }
        public Nullable<int> Id_Tipo { get; set; }
        public Nullable<System.DateTime> Fecha_Proceso { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
    
        public virtual combo_tipo combo_tipo { get; set; }
        public virtual entidades entidades { get; set; }
        public virtual ICollection<combo_sub_categoria> combo_sub_categoria { get; set; }
        public virtual ICollection<ingresos> ingresos { get; set; }
    }
}
