//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS_DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class entidades
    {
        public entidades()
        {
            this.cierre_mes = new HashSet<cierre_mes>();
            this.combo_categoria = new HashSet<combo_categoria>();
            this.combo_sub_categoria = new HashSet<combo_sub_categoria>();
            this.ingesos_mensuales = new HashSet<ingesos_mensuales>();
            this.ingresos = new HashSet<ingresos>();
            this.login = new HashSet<login>();
            this.egresos_mensuales = new HashSet<egresos_mensuales>();
        }
    
        public int id { get; set; }
        public System.DateTime Fecha_Creado { get; set; }
        public string Entidad { get; set; }
        public string Entidad_hash { get; set; }
        public string Clave_Temporal { get; set; }
        public string Observaciones { get; set; }
        public string Activo { get; set; }
    
        public virtual ICollection<cierre_mes> cierre_mes { get; set; }
        public virtual ICollection<combo_categoria> combo_categoria { get; set; }
        public virtual ICollection<combo_sub_categoria> combo_sub_categoria { get; set; }
        public virtual ICollection<ingesos_mensuales> ingesos_mensuales { get; set; }
        public virtual ICollection<ingresos> ingresos { get; set; }
        public virtual ICollection<login> login { get; set; }
        public virtual ICollection<egresos_mensuales> egresos_mensuales { get; set; }
    }
}
