//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS_DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingresos
    {
        public long id { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> Id_Entidad { get; set; }
        public Nullable<int> Id_Tipo { get; set; }
        public Nullable<int> Id_Categoria { get; set; }
        public Nullable<int> Id_SubCategoria { get; set; }
        public Nullable<int> Id_Forma_Pago { get; set; }
        public string Observación { get; set; }
        public Nullable<double> Precio { get; set; }
        public bool Activo { get; set; }
    
        public virtual combo_categoria combo_categoria { get; set; }
        public virtual combo_forma_pago combo_forma_pago { get; set; }
        public virtual combo_sub_categoria combo_sub_categoria { get; set; }
        public virtual combo_tipo combo_tipo { get; set; }
        public virtual entidades entidades { get; set; }
    }
}
