//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS_DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_conexiones
    {
        public int Id { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public string Entidad { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public string Ip_Cliente { get; set; }
        public string Bloqueado { get; set; }
        public string Version_Actual { get; set; }
    }
}
