//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS_DLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mmsEntities : DbContext
    {
        public mmsEntities()
            : base("name=mmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cierre_mes> cierre_mes { get; set; }
        public virtual DbSet<combo_categoria> combo_categoria { get; set; }
        public virtual DbSet<combo_forma_pago> combo_forma_pago { get; set; }
        public virtual DbSet<combo_mes> combo_mes { get; set; }
        public virtual DbSet<combo_sub_categoria> combo_sub_categoria { get; set; }
        public virtual DbSet<combo_tipo> combo_tipo { get; set; }
        public virtual DbSet<entidades> entidades { get; set; }
        public virtual DbSet<ingesos_mensuales> ingesos_mensuales { get; set; }
        public virtual DbSet<ingresos> ingresos { get; set; }
        public virtual DbSet<log_conexiones> log_conexiones { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<mensajes> mensajes { get; set; }
        public virtual DbSet<egresos_mensuales> egresos_mensuales { get; set; }
    }
}
